const CartActionTypes = {
    TOGGLE_CART_VISIBILITY : 'TOGGLE_CART_VISIBILITY',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    REDUCE_CART_ITEM_QTY: 'REDUCE_CART_ITEM_QTY',
    CLEAR_CART: 'CLEAR_CART'
};

export default CartActionTypes;